name: blitzit_flutter
description: A modern Flutter desktop application for productivity and task management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  material_color_utilities: ^0.11.1
  dynamic_color: ^1.6.8
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^13.2.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  
  # Animations
  animations: ^2.0.11
  lottie: ^3.1.0
  
  # Charts
  fl_chart: ^0.66.2
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Windows Desktop Support
  window_manager: ^0.3.8
  
  # File System
  path_provider: ^2.1.1
  
  # JSON Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

# Dependency overrides to resolve version conflicts
dependency_overrides:
  material_color_utilities: ^0.11.1
  web: ^0.5.1
